include("ccma_parameterisation.jl")
include("ccma_steady_state.jl")

println("hello bestie")

ccma_model_00((
    lead_log_c, lead_log_c_p, lead_log_h, lead_log_h_p, lead_log_i, lead_log_k, lead_log_y, lead_log_b, lead_log_n, lead_log_n_p, lead_log_w, lead_log_w_p, lead_log_π, lead_log_q, lead_log_R, lead_log_λ, lead_log_x_p, lead_log_x_w, lead_log_x_w_p, lead_log_r_k, lead_log_q_k, lead_log_j, lead_log_z, lead_log_a, lead_log_e, lead_log_u_c, lead_log_u_c_p, lead_log_u_h, lead_log_u_h_p, lead_log_u_n, lead_log_u_n_p, lead_log_div, lead_log_div_p, lead_log_ω, lead_log_ω_p, lead_log_π_Α, lead_log_π_l1, lead_log_π_l2, lead_log_π_l3, lead_log_bnot, lead_maxlev, lead_log_rnot,
    log_c, log_c_p, log_h, log_h_p, log_i, log_k, log_y, log_b, log_n, log_n_p, log_w, log_w_p, log_π, log_q, log_R, log_λ, log_x_p, log_x_w, log_x_w_p, log_r_k, log_q_k, log_j, log_z, log_a, log_e, log_u_c, log_u_c_p, log_u_h, log_u_h_p, log_u_n, log_u_n_p, log_div, log_div_p, log_ω, log_ω_p, log_π_Α, log_π_l1, log_π_l2, log_π_l3, log_bnot, maxlev, log_rnot,
    lag_log_c, lag_log_c_p, lag_log_h, lag_log_h_p, lag_log_i, lag_log_k, lag_log_y, lag_log_b, lag_log_n, lag_log_n_p, lag_log_w, lag_log_w_p, lag_log_π, lag_log_q, lag_log_R, lag_log_λ, lag_log_x_p, lag_log_x_w, lag_log_x_w_p, lag_log_r_k, lag_log_q_k, lag_log_j, lag_log_z, lag_log_a, lag_log_e, lag_log_u_c, lag_log_u_c_p, lag_log_u_h, lag_log_u_h_p, lag_log_u_n, lag_log_u_n_p, lag_log_div, lag_log_div_p, lag_log_ω, lag_log_ω_p, lag_log_π_Α, lag_log_π_l1, lag_log_π_l2, lag_log_π_l3, lag_log_bnot, lag_maxlev, lag_log_rnot
)) = [
    exp(log_c) + exp(log_q) * (exp(log_h) - exp(lag_log_h)) + exp(log_i) - (exp(lag_log_R) * exp(lag_log_b)) / exp(log_π) - (exp(log_w) * exp(log_n)) / exp(log_x_w) - exp(log_r_k) * exp(lag_log_k) + exp(log_b) - exp(log_div),
    exp(log_u_c) * exp(log_q_k) * (1 - (ccma_params.φ / 2) * (1 / ccma_ss.i_ss) * (exp(log_i) - exp(lag_log_i))) - exp(log_u_c) + ccma_params.β * exp(lead_log_u_c) * exp(lead_log_q_k) * ccma_params.φ * (1 / ccma_ss.i_ss) * (exp(lead_log_i) - exp(log_i)),
    exp(log_u_c) * exp(log_q_k) / exp(log_a) - ccma_params.β * exp(lead_log_u_c) * (exp(lead_log_r_k) + exp(lead_log_q_k) * (1 - ccma_params.δ_k) / exp(lead_log_a)),
    exp(log_k) - exp(log_a) * (exp(log_i) - (ccma_params.φ / 2) * (1 / ccma_ss.i_ss) * (exp(log_i) - exp(lag_log_i))^2) - (1 - ccma_params.δ_k) * exp(lag_log_k),
    exp(log_u_c) - ccma_params.β * exp(lead_log_u_c) * exp(log_R) / exp(lead_log_π),
    exp(log_w) / exp(log_x_w) * exp(log_u_c) - exp(log_u_n),
    exp(log_q) * exp(log_u_c) - exp(log_u_h) - ccma_params.β * exp(lead_log_q) * exp(lead_log_u_c),
    exp(log_c_p) + exp(log_q) * (exp(log_h_p) - exp(lag_log_h_p)) + (exp(lag_log_R) * exp(lag_log_b)) / exp(log_π) - (exp(log_w_p) * exp(log_n_p)) / exp(log_x_w_p) - exp(log_b) - exp(log_div_p),
    (1 - exp(log_λ)) * exp(log_u_c_p) - ccma_params.βp * ((exp(log_R) - ccma_params.γ * exp(lead_log_λ)) * exp(lead_log_u_c_p) / exp(lead_log_π)),
    log_w_p - log_x_w_p + log_u_c_p - log_u_n_p,
    exp(log_q) * exp(log_u_c_p) - exp(log_u_h_p) - ccma_params.βp * exp(lead_log_q) * exp(lead_log_u_c_p) - exp(log_u_c_p) * exp(log_λ) * (1 - ccma_params.γ) * ccma_params.m * exp(log_q),
    log_y - (1 - ccma_params.σ) * (ccma_params.α) * log_n - ccma_params.σ * (1 - ccma_params.α) * log_n_p - ccma_params.α * lag_log_k,
    (1 - ccma_params.α) * (ccma_params.σ) * exp(log_y) - exp(log_x_p) * exp(log_w) * exp(log_n),
    (1 - ccma_params.α) * ccma_params.σ * exp(log_y) - exp(log_x_p) * exp(log_w_p) * exp(log_n_p),
    ccma_params.α * exp(log_y) - exp(log_x_p) * exp(log_r_k) * exp(lag_log_k),
    log_π - log(ccma_ss.π_ss) - ccma_params.β * (lead_log_π - log(ccma_ss.π_ss)) + ccma_params.ε_π * (log_x_p - log(ccma_ss.x_p_ss)),
    log_ω - log(ccma_ss.π_ss) - ccma_params.β * (lead_log_ω - log(ccma_ss.π_ss)) + ccma_params.ε_w * (log_x_w - log(ccma_ss.x_w_ss)),
    log_ω_p - log(ccma_ss.π_ss) - ccma_params.βp * (lead_log_ω_p - log(ccma_ss.π_ss)) + ccma_params.ε_wp * (log_x_w_p - log(ccma_ss.x_w_p_ss)),
    log_rnot - ccma_params.r_R * lag_log_R - (1 - ccma_params.r_R) * ccma_params.r_π * (log_π_Α - log(ccma_ss.π_A_ss)) - (1 - ccma_params.r_R) * ccma_params.r_y * (log_y - log(ccma_ss.y_ss)) - (1 - ccma_params.r_R) * ccma_ss.R_ss,
    exp(log_h) + exp(log_h_p) - 1,
    log_j - (1 - ccma_params.ρ_J) * log(ccma_ss.j_ss) - ccma_params.ρ_J * lag_log_j,
    log_z - ccma_params.ρ_Z * lag_log_z,
    log_a - ccma_params.ρ_K * lag_log_a,
    log_e - ccma_params.ρ_R * lag_log_e,
    exp(log_u_c) - exp(log_z) * ccma_params.Γ_c * (1 / (exp(log_c) - ccma_params.ε_c * exp(lag_log_c))),
    exp(log_u_c_p) - exp(log_z) * ccma_params.Γ_c_p * (1 / (exp(log_c_p) - ccma_params.ε_c * exp(lag_log_c_p))),
    exp(log_u_h) - exp(log_z) * exp(log_j) * ccma_params.Γ_h * (1 / (exp(log_h) - ccma_params.ε_h * exp(lag_log_h))),
    exp(log_u_h_p) - exp(log_z) * exp(log_j) * ccma_params.Γ_h_p * (1 / (exp(log_h_p) - ccma_params.ε_h * exp(lag_log_h_p))),
    exp(log_u_n) + exp(log_z) * exp(log_n)^ccma_params.η,
    exp(log_u_n_p) + exp(log_z) * exp(log_n_p)^ccma_params.η,
    exp(log_div) - ((exp(log_x_p) - 1) / exp(log_x_p)) * exp(log_y) - ((exp(log_x_w) - 1) / exp(log_x_w)) * exp(log_w) * exp(log_n),
    exp(log_div_p) - ((exp(log_x_w_p) - 1) / exp(log_x_w_p)) * exp(log_w_p) * exp(log_n_p),
    log_ω - log_w - log_π + lag_log_w,
    log_ω_p - log_w_p - log_π + lag_log_w_p,
    log_π_Α - 0.25 * (log_π_l1 + log_π_l2 + log_π_l3),
    log_π_l1 - lag_log_π,
    log_π_l2 - lag_log_π_l1,
    log_π_l3 - lag_log_π_l2,
    exp(log_b) - exp(log_bnot),
    exp(log_bnot) - (1 - ccma_params.γ) * exp(lag_log_b) / exp(lag_log_π) - (1 - ccma_params.γ) * ccma_params.m * exp(log_q) * exp(log_h_p),
    maxlev - exp(log_b) + exp(log_bnot),
    log_R - log_rnot
]

ccma_model_01((
    lead_log_c, lead_log_c_p, lead_log_h, lead_log_h_p, lead_log_i, lead_log_k, lead_log_y, lead_log_b, lead_log_n, lead_log_n_p, lead_log_w, lead_log_w_p, lead_log_π, lead_log_q, lead_log_R, lead_log_λ, lead_log_x_p, lead_log_x_w, lead_log_x_w_p, lead_log_r_k, lead_log_q_k, lead_log_j, lead_log_z, lead_log_a, lead_log_e, lead_log_u_c, lead_log_u_c_p, lead_log_u_h, lead_log_u_h_p, lead_log_u_n, lead_log_u_n_p, lead_log_div, lead_log_div_p, lead_log_ω, lead_log_ω_p, lead_log_π_Α, lead_log_bnot, lead_maxlev, lead_log_rnot,
    log_c, log_c_p, log_h, log_h_p, log_i, log_k, log_y, log_b, log_n, log_n_p, log_w, log_w_p, log_π, log_q, log_R, log_λ, log_x_p, log_x_w, log_x_w_p, log_r_k, log_q_k, log_j, log_z, log_a, log_e, log_u_c, log_u_c_p, log_u_h, log_u_h_p, log_u_n, log_u_n_p, log_div, log_div_p, log_ω, log_ω_p, log_π_Α, log_bnot, maxlev, log_rnot,
    lag_log_c, lag_log_c_p, lag_log_h, lag_log_h_p, lag_log_i, lag_log_k, lag_log_y, lag_log_b, lag_log_n, lag_log_n_p, lag_log_w, lag_log_w_p, lag_log_π, lag_log_q, lag_log_R, lag_log_λ, lag_log_x_p, lag_log_x_w, lag_log_x_w_p, lag_log_r_k, lag_log_q_k, lag_log_j, lag_log_z, lag_log_a, lag_log_e, lag_log_u_c, lag_log_u_c_p, lag_log_u_h, lag_log_u_h_p, lag_log_u_n, lag_log_u_n_p, lag_log_div, lag_log_div_p, lag_log_ω, lag_log_ω_p, lag_log_π_Α, lag_log_bnot, lag_maxlev, lag_log_rnot
)) = [
    exp(log_c) + exp(log_q) * (exp(log_h) - exp(lag_log_h)) + exp(log_i) - (exp(lag_log_R) * exp(lag_log_b)) / exp(log_π) - (exp(log_w) * exp(log_n)) / exp(log_x_w) - exp(log_r_k) * exp(lag_log_k) + exp(log_b) - exp(log_div),
    exp(log_u_c) * exp(log_q_k) * (1 - (ccma_params.φ / 2) * (1 / ccma_ss.i_ss) * (exp(log_i) - exp(lag_log_i))) - exp(log_u_c) + ccma_params.β * exp(lead_log_u_c) * exp(lead_log_q_k) * ccma_params.φ * (1 / ccma_ss.i_ss) * (exp(lead_log_i) - exp(log_i)),
    exp(log_u_c) * exp(log_q_k) / exp(log_a) - ccma_params.β * exp(lead_log_u_c) * (exp(lead_log_r_k) + exp(lead_log_q_k) * (1 - ccma_params.δ_k) / exp(lead_log_a)),
    exp(log_k) - exp(log_a) * (exp(log_i) - (ccma_params.φ / 2) * (1 / ccma_ss.i_ss) * (exp(log_i) - exp(lag_log_i))^2) - (1 - ccma_params.δ_k) * exp(lag_log_k),
    exp(log_u_c) - ccma_params.β * exp(lead_log_u_c) * exp(log_R) / exp(lead_log_π),
    exp(log_w) / exp(log_x_w) * exp(log_u_c) - exp(log_u_n),
    exp(log_q) * exp(log_u_c) - exp(log_u_h) - ccma_params.β * exp(lead_log_q) * exp(lead_log_u_c),
    exp(log_c_p) + exp(log_q) * (exp(log_h_p) - exp(lag_log_h_p)) + (exp(lag_log_R) * exp(lag_log_b)) / exp(log_π) - (exp(log_w_p) * exp(log_n_p)) / exp(log_x_w_p) - exp(log_b) - exp(log_div_p),
    (1 - exp(log_λ)) * exp(log_u_c_p) - ccma_params.βp * ((exp(log_R) - ccma_params.γ * exp(lead_log_λ)) * exp(lead_log_u_c_p) / exp(lead_log_π)),
    log_w_p - log_x_w_p + log_u_c_p - log_u_n_p,
    exp(log_q) * exp(log_u_c_p) - exp(log_u_h_p) - ccma_params.βp * exp(lead_log_q) * exp(lead_log_u_c_p) - exp(log_u_c_p) * exp(log_λ) * (1 - ccma_params.γ) * ccma_params.m * exp(log_q),
    log_y - (1 - ccma_params.σ) * (ccma_params.α) * log_n - ccma_params.σ * (1 - ccma_params.α) * log_n_p - ccma_params.α * lag_log_k,
    (1 - ccma_params.α) * (ccma_params.σ) * exp(log_y) - exp(log_x_p) * exp(log_w) * exp(log_n),
    (1 - ccma_params.α) * ccma_params.σ * exp(log_y) - exp(log_x_p) * exp(log_w_p) * exp(log_n_p),
    ccma_params.α * exp(log_y) - exp(log_x_p) * exp(log_r_k) * exp(lag_log_k),
    log_π - log(ccma_ss.π_ss) - ccma_params.β * (lead_log_π - log(ccma_ss.π_ss)) + ccma_params.ε_π * (log_x_p - log(ccma_ss.x_p_ss)),
    log_ω - log(ccma_ss.π_ss) - ccma_params.β * (lead_log_ω - log(ccma_ss.π_ss)) + ccma_params.ε_w * (log_x_w - log(ccma_ss.x_w_ss)),
    log_ω_p - log(ccma_ss.π_ss) - ccma_params.βp * (lead_log_ω_p - log(ccma_ss.π_ss)) + ccma_params.ε_wp * (log_x_w_p - log(ccma_ss.x_w_p_ss)),
    log_rnot - ccma_params.r_R * lag_log_R - (1 - ccma_params.r_R) * ccma_params.r_π * (log_π_Α - log(ccma_ss.π_A_ss)) - (1 - ccma_params.r_R) * ccma_params.r_y * (log_y - log(ccma_ss.y_ss)) - (1 - ccma_params.r_R) * ccma_ss.R_ss,
    exp(log_h) + exp(log_h_p) - 1,
    log_j - (1 - ccma_params.ρ_J) * log(ccma_ss.j_ss) - ccma_params.ρ_J * lag_log_j,
    log_z - ccma_params.ρ_Z * lag_log_z,
    log_a - ccma_params.ρ_K * lag_log_a,
    log_e - ccma_params.ρ_R * lag_log_e,
    exp(log_u_c) - exp(log_z) * ccma_params.Γ_c * (1 / (exp(log_c) - ccma_params.ε_c * exp(lag_log_c))),
    exp(log_u_c_p) - exp(log_z) * ccma_params.Γ_c_p * (1 / (exp(log_c_p) - ccma_params.ε_c * exp(lag_log_c_p))),
    exp(log_u_h) - exp(log_z) * exp(log_j) * ccma_params.Γ_h * (1 / (exp(log_h) - ccma_params.ε_h * exp(lag_log_h))),
    exp(log_u_h_p) - exp(log_z) * exp(log_j) * ccma_params.Γ_h_p * (1 / (exp(log_h_p) - ccma_params.ε_h * exp(lag_log_h_p))),
    exp(log_u_n) + exp(log_z) * exp(log_n)^ccma_params.η,
    exp(log_u_n_p) + exp(log_z) * exp(log_n_p)^ccma_params.η,
    exp(log_div) - ((exp(log_x_p) - 1) / exp(log_x_p)) * exp(log_y) - ((exp(log_x_w) - 1) / exp(log_x_w)) * exp(log_w) * exp(log_n),
    exp(log_div_p) - ((exp(log_x_w_p) - 1) / exp(log_x_w_p)) * exp(log_w_p) * exp(log_n_p),
    log_ω - log_w - log_π + lag_log_w,
    log_ω_p - log_w_p - log_π + lag_log_w_p,
    log_π_Α - log_π, #+ lag_log_π_Α
    exp(log_b) - exp(log_bnot),
    exp(log_bnot) - (1 - ccma_params.γ) * exp(lag_log_b) / exp(lag_log_π) - (1 - ccma_params.γ) * ccma_params.m * exp(log_q) * exp(log_h_p),
    maxlev - exp(log_b) + exp(log_bnot),
    log_R
]

ccma_model_10((
    lead_log_c, lead_log_c_p, lead_log_h, lead_log_h_p, lead_log_i, lead_log_k, lead_log_y, lead_log_b, lead_log_n, lead_log_n_p, lead_log_w, lead_log_w_p, lead_log_π, lead_log_q, lead_log_R, lead_log_λ, lead_log_x_p, lead_log_x_w, lead_log_x_w_p, lead_log_r_k, lead_log_q_k, lead_log_j, lead_log_z, lead_log_a, lead_log_e, lead_log_u_c, lead_log_u_c_p, lead_log_u_h, lead_log_u_h_p, lead_log_u_n, lead_log_u_n_p, lead_log_div, lead_log_div_p, lead_log_ω, lead_log_ω_p, lead_log_π_Α, lead_log_bnot, lead_maxlev, lead_log_rnot,
    log_c, log_c_p, log_h, log_h_p, log_i, log_k, log_y, log_b, log_n, log_n_p, log_w, log_w_p, log_π, log_q, log_R, log_λ, log_x_p, log_x_w, log_x_w_p, log_r_k, log_q_k, log_j, log_z, log_a, log_e, log_u_c, log_u_c_p, log_u_h, log_u_h_p, log_u_n, log_u_n_p, log_div, log_div_p, log_ω, log_ω_p, log_π_Α, log_bnot, maxlev, log_rnot,
    lag_log_c, lag_log_c_p, lag_log_h, lag_log_h_p, lag_log_i, lag_log_k, lag_log_y, lag_log_b, lag_log_n, lag_log_n_p, lag_log_w, lag_log_w_p, lag_log_π, lag_log_q, lag_log_R, lag_log_λ, lag_log_x_p, lag_log_x_w, lag_log_x_w_p, lag_log_r_k, lag_log_q_k, lag_log_j, lag_log_z, lag_log_a, lag_log_e, lag_log_u_c, lag_log_u_c_p, lag_log_u_h, lag_log_u_h_p, lag_log_u_n, lag_log_u_n_p, lag_log_div, lag_log_div_p, lag_log_ω, lag_log_ω_p, lag_log_π_Α, lag_log_bnot, lag_maxlev, lag_log_rnot
)) = [
    exp(log_c) + exp(log_q) * (exp(log_h) - exp(lag_log_h)) + exp(log_i) - (exp(lag_log_R) * exp(lag_log_b)) / exp(log_π) - (exp(log_w) * exp(log_n)) / exp(log_x_w) - exp(log_r_k) * exp(lag_log_k) + exp(log_b) - exp(log_div),
    exp(log_u_c) * exp(log_q_k) * (1 - (ccma_params.φ / 2) * (1 / ccma_ss.i_ss) * (exp(log_i) - exp(lag_log_i))) - exp(log_u_c) + ccma_params.β * exp(lead_log_u_c) * exp(lead_log_q_k) * ccma_params.φ * (1 / ccma_ss.i_ss) * (exp(lead_log_i) - exp(log_i)),
    exp(log_u_c) * exp(log_q_k) / exp(log_a) - ccma_params.β * exp(lead_log_u_c) * (exp(lead_log_r_k) + exp(lead_log_q_k) * (1 - ccma_params.δ_k) / exp(lead_log_a)),
    exp(log_k) - exp(log_a) * (exp(log_i) - (ccma_params.φ / 2) * (1 / ccma_ss.i_ss) * (exp(log_i) - exp(lag_log_i))^2) - (1 - ccma_params.δ_k) * exp(lag_log_k),
    exp(log_u_c) - ccma_params.β * exp(lead_log_u_c) * exp(log_R) / exp(lead_log_π),
    exp(log_w) / exp(log_x_w) * exp(log_u_c) - exp(log_u_n),
    exp(log_q) * exp(log_u_c) - exp(log_u_h) - ccma_params.β * exp(lead_log_q) * exp(lead_log_u_c),
    exp(log_c_p) + exp(log_q) * (exp(log_h_p) - exp(lag_log_h_p)) + (exp(lag_log_R) * exp(lag_log_b)) / exp(log_π) - (exp(log_w_p) * exp(log_n_p)) / exp(log_x_w_p) - exp(log_b) - exp(log_div_p),
    (1 - exp(log_λ)) * exp(log_u_c_p) - ccma_params.βp * ((exp(log_R) - ccma_params.γ * exp(lead_log_λ)) * exp(lead_log_u_c_p) / exp(lead_log_π)),
    log_w_p - log_x_w_p + log_u_c_p - log_u_n_p,
    exp(log_q) * exp(log_u_c_p) - exp(log_u_h_p) - ccma_params.βp * exp(lead_log_q) * exp(lead_log_u_c_p) - exp(log_u_c_p) * exp(log_λ) * (1 - ccma_params.γ) * ccma_params.m * exp(log_q),
    log_y - (1 - ccma_params.σ) * (ccma_params.α) * log_n - ccma_params.σ * (1 - ccma_params.α) * log_n_p - ccma_params.α * lag_log_k,
    (1 - ccma_params.α) * (ccma_params.σ) * exp(log_y) - exp(log_x_p) * exp(log_w) * exp(log_n),
    (1 - ccma_params.α) * ccma_params.σ * exp(log_y) - exp(log_x_p) * exp(log_w_p) * exp(log_n_p),
    ccma_params.α * exp(log_y) - exp(log_x_p) * exp(log_r_k) * exp(lag_log_k),
    log_π - log(ccma_ss.π_ss) - ccma_params.β * (lead_log_π - log(ccma_ss.π_ss)) + ccma_params.ε_π * (log_x_p - log(ccma_ss.x_p_ss)),
    log_ω - log(ccma_ss.π_ss) - ccma_params.β * (lead_log_ω - log(ccma_ss.π_ss)) + ccma_params.ε_w * (log_x_w - log(ccma_ss.x_w_ss)),
    log_ω_p - log(ccma_ss.π_ss) - ccma_params.βp * (lead_log_ω_p - log(ccma_ss.π_ss)) + ccma_params.ε_wp * (log_x_w_p - log(ccma_ss.x_w_p_ss)),
    log_rnot - ccma_params.r_R * lag_log_R - (1 - ccma_params.r_R) * ccma_params.r_π * (log_π_Α - log(ccma_ss.π_A_ss)) - (1 - ccma_params.r_R) * ccma_params.r_y * (log_y - log(ccma_ss.y_ss)) - (1 - ccma_params.r_R) * ccma_ss.R_ss,
    exp(log_h) + exp(log_h_p) - 1,
    log_j - (1 - ccma_params.ρ_J) * log(ccma_ss.j_ss) - ccma_params.ρ_J * lag_log_j,
    log_z - ccma_params.ρ_Z * lag_log_z,
    log_a - ccma_params.ρ_K * lag_log_a,
    log_e - ccma_params.ρ_R * lag_log_e,
    exp(log_u_c) - exp(log_z) * ccma_params.Γ_c * (1 / (exp(log_c) - ccma_params.ε_c * exp(lag_log_c))),
    exp(log_u_c_p) - exp(log_z) * ccma_params.Γ_c_p * (1 / (exp(log_c_p) - ccma_params.ε_c * exp(lag_log_c_p))),
    exp(log_u_h) - exp(log_z) * exp(log_j) * ccma_params.Γ_h * (1 / (exp(log_h) - ccma_params.ε_h * exp(lag_log_h))),
    exp(log_u_h_p) - exp(log_z) * exp(log_j) * ccma_params.Γ_h_p * (1 / (exp(log_h_p) - ccma_params.ε_h * exp(lag_log_h_p))),
    exp(log_u_n) + exp(log_z) * exp(log_n)^ccma_params.η,
    exp(log_u_n_p) + exp(log_z) * exp(log_n_p)^ccma_params.η,
    exp(log_div) - ((exp(log_x_p) - 1) / exp(log_x_p)) * exp(log_y) - ((exp(log_x_w) - 1) / exp(log_x_w)) * exp(log_w) * exp(log_n),
    exp(log_div_p) - ((exp(log_x_w_p) - 1) / exp(log_x_w_p)) * exp(log_w_p) * exp(log_n_p),
    log_ω - log_w - log_π + lag_log_w,
    log_ω_p - log_w_p - log_π + lag_log_w_p,
    log_π_Α - log_π, #+ lag_log_π_Α
    exp(log_λ),
    exp(log_bnot) - (1 - ccma_params.γ) * exp(lag_log_b) / exp(lag_log_π) - (1 - ccma_params.γ) * ccma_params.m * exp(log_q) * exp(log_h_p),
    maxlev - exp(log_b) + exp(log_bnot),
    log_R
]

ccma_model_11((
    lead_log_c, lead_log_c_p, lead_log_h, lead_log_h_p, lead_log_i, lead_log_k, lead_log_y, lead_log_b, lead_log_n, lead_log_n_p, lead_log_w, lead_log_w_p, lead_log_π, lead_log_q, lead_log_R, lead_log_λ, lead_log_x_p, lead_log_x_w, lead_log_x_w_p, lead_log_r_k, lead_log_q_k, lead_log_j, lead_log_z, lead_log_a, lead_log_e, lead_log_u_c, lead_log_u_c_p, lead_log_u_h, lead_log_u_h_p, lead_log_u_n, lead_log_u_n_p, lead_log_div, lead_log_div_p, lead_log_ω, lead_log_ω_p, lead_log_π_Α, lead_log_bnot, lead_maxlev, lead_log_rnot,
    log_c, log_c_p, log_h, log_h_p, log_i, log_k, log_y, log_b, log_n, log_n_p, log_w, log_w_p, log_π, log_q, log_R, log_λ, log_x_p, log_x_w, log_x_w_p, log_r_k, log_q_k, log_j, log_z, log_a, log_e, log_u_c, log_u_c_p, log_u_h, log_u_h_p, log_u_n, log_u_n_p, log_div, log_div_p, log_ω, log_ω_p, log_π_Α, log_bnot, maxlev, log_rnot,
    lag_log_c, lag_log_c_p, lag_log_h, lag_log_h_p, lag_log_i, lag_log_k, lag_log_y, lag_log_b, lag_log_n, lag_log_n_p, lag_log_w, lag_log_w_p, lag_log_π, lag_log_q, lag_log_R, lag_log_λ, lag_log_x_p, lag_log_x_w, lag_log_x_w_p, lag_log_r_k, lag_log_q_k, lag_log_j, lag_log_z, lag_log_a, lag_log_e, lag_log_u_c, lag_log_u_c_p, lag_log_u_h, lag_log_u_h_p, lag_log_u_n, lag_log_u_n_p, lag_log_div, lag_log_div_p, lag_log_ω, lag_log_ω_p, lag_log_π_Α, lag_log_bnot, lag_maxlev, lag_log_rnot
)) = [
    exp(log_c) + exp(log_q) * (exp(log_h) - exp(lag_log_h)) + exp(log_i) - (exp(lag_log_R) * exp(lag_log_b)) / exp(log_π) - (exp(log_w) * exp(log_n)) / exp(log_x_w) - exp(log_r_k) * exp(lag_log_k) + exp(log_b) - exp(log_div),
    exp(log_u_c) * exp(log_q_k) * (1 - (ccma_params.φ / 2) * (1 / ccma_ss.i_ss) * (exp(log_i) - exp(lag_log_i))) - exp(log_u_c) + ccma_params.β * exp(lead_log_u_c) * exp(lead_log_q_k) * ccma_params.φ * (1 / ccma_ss.i_ss) * (exp(lead_log_i) - exp(log_i)),
    exp(log_u_c) * exp(log_q_k) / exp(log_a) - ccma_params.β * exp(lead_log_u_c) * (exp(lead_log_r_k) + exp(lead_log_q_k) * (1 - ccma_params.δ_k) / exp(lead_log_a)),
    exp(log_k) - exp(log_a) * (exp(log_i) - (ccma_params.φ / 2) * (1 / ccma_ss.i_ss) * (exp(log_i) - exp(lag_log_i))^2) - (1 - ccma_params.δ_k) * exp(lag_log_k),
    exp(log_u_c) - ccma_params.β * exp(lead_log_u_c) * exp(log_R) / exp(lead_log_π),
    exp(log_w) / exp(log_x_w) * exp(log_u_c) - exp(log_u_n),
    exp(log_q) * exp(log_u_c) - exp(log_u_h) - ccma_params.β * exp(lead_log_q) * exp(lead_log_u_c),
    exp(log_c_p) + exp(log_q) * (exp(log_h_p) - exp(lag_log_h_p)) + (exp(lag_log_R) * exp(lag_log_b)) / exp(log_π) - (exp(log_w_p) * exp(log_n_p)) / exp(log_x_w_p) - exp(log_b) - exp(log_div_p),
    (1 - exp(log_λ)) * exp(log_u_c_p) - ccma_params.βp * ((exp(log_R) - ccma_params.γ * exp(lead_log_λ)) * exp(lead_log_u_c_p) / exp(lead_log_π)),
    log_w_p - log_x_w_p + log_u_c_p - log_u_n_p,
    exp(log_q) * exp(log_u_c_p) - exp(log_u_h_p) - ccma_params.βp * exp(lead_log_q) * exp(lead_log_u_c_p) - exp(log_u_c_p) * exp(log_λ) * (1 - ccma_params.γ) * ccma_params.m * exp(log_q),
    log_y - (1 - ccma_params.σ) * (ccma_params.α) * log_n - ccma_params.σ * (1 - ccma_params.α) * log_n_p - ccma_params.α * lag_log_k,
    (1 - ccma_params.α) * (ccma_params.σ) * exp(log_y) - exp(log_x_p) * exp(log_w) * exp(log_n),
    (1 - ccma_params.α) * ccma_params.σ * exp(log_y) - exp(log_x_p) * exp(log_w_p) * exp(log_n_p),
    ccma_params.α * exp(log_y) - exp(log_x_p) * exp(log_r_k) * exp(lag_log_k),
    log_π - log(ccma_ss.π_ss) - ccma_params.β * (lead_log_π - log(ccma_ss.π_ss)) + ccma_params.ε_π * (log_x_p - log(ccma_ss.x_p_ss)),
    log_ω - log(ccma_ss.π_ss) - ccma_params.β * (lead_log_ω - log(ccma_ss.π_ss)) + ccma_params.ε_w * (log_x_w - log(ccma_ss.x_w_ss)),
    log_ω_p - log(ccma_ss.π_ss) - ccma_params.βp * (lead_log_ω_p - log(ccma_ss.π_ss)) + ccma_params.ε_wp * (log_x_w_p - log(ccma_ss.x_w_p_ss)),
    log_rnot - ccma_params.r_R * lag_log_R - (1 - ccma_params.r_R) * ccma_params.r_π * (log_π_Α - log(ccma_ss.π_A_ss)) - (1 - ccma_params.r_R) * ccma_params.r_y * (log_y - log(ccma_ss.y_ss)) - (1 - ccma_params.r_R) * ccma_ss.R_ss,
    exp(log_h) + exp(log_h_p) - 1,
    log_j - (1 - ccma_params.ρ_J) * log(ccma_ss.j_ss) - ccma_params.ρ_J * lag_log_j,
    log_z - ccma_params.ρ_Z * lag_log_z,
    log_a - ccma_params.ρ_K * lag_log_a,
    log_e - ccma_params.ρ_R * lag_log_e,
    exp(log_u_c) - exp(log_z) * ccma_params.Γ_c * (1 / (exp(log_c) - ccma_params.ε_c * exp(lag_log_c))),
    exp(log_u_c_p) - exp(log_z) * ccma_params.Γ_c_p * (1 / (exp(log_c_p) - ccma_params.ε_c * exp(lag_log_c_p))),
    exp(log_u_h) - exp(log_z) * exp(log_j) * ccma_params.Γ_h * (1 / (exp(log_h) - ccma_params.ε_h * exp(lag_log_h))),
    exp(log_u_h_p) - exp(log_z) * exp(log_j) * ccma_params.Γ_h_p * (1 / (exp(log_h_p) - ccma_params.ε_h * exp(lag_log_h_p))),
    exp(log_u_n) + exp(log_z) * exp(log_n)^ccma_params.η,
    exp(log_u_n_p) + exp(log_z) * exp(log_n_p)^ccma_params.η,
    exp(log_div) - ((exp(log_x_p) - 1) / exp(log_x_p)) * exp(log_y) - ((exp(log_x_w) - 1) / exp(log_x_w)) * exp(log_w) * exp(log_n),
    exp(log_div_p) - ((exp(log_x_w_p) - 1) / exp(log_x_w_p)) * exp(log_w_p) * exp(log_n_p),
    log_ω - log_w - log_π + lag_log_w,
    log_ω_p - log_w_p - log_π + lag_log_w_p,
    log_π_Α - log_π, #+ lag_log_π_Α
    exp(log_λ),
    exp(log_bnot) - (1 - ccma_params.γ) * exp(lag_log_b) / exp(lag_log_π) - (1 - ccma_params.γ) * ccma_params.m * exp(log_q) * exp(log_h_p),
    maxlev - exp(log_b) + exp(log_bnot),
    log_R
]

println("goodbye bestie")